# The following code is taken from: https://github.com/SummerOfBitcoin/code-challenge-2024-Nesopie/blob/840aeb58dd68cba3fba33f96d71ea0790c1840a8/src/features/script/op_codes.ts

OP_CODES = {
    """ 'OP_0': b'\x00',
    'OP_PUSHBYTES_1': b'\x01',
    'OP_PUSHBYTES_2': b'\x02',
    'OP_PUSHBYTES_3': b'\x03',
    'OP_PUSHBYTES_4': b'\x04',
    'OP_PUSHBYTES_5': b'\x05',
    'OP_PUSHBYTES_6': b'\x06',
    'OP_PUSHBYTES_7': b'\x07',
    'OP_PUSHBYTES_8': b'\x08',
    'OP_PUSHBYTES_9': b'\x09',
    'OP_PUSHBYTES_10': b'\x0a',
    'OP_PUSHBYTES_11': b'\x0b',
    'OP_PUSHBYTES_12': b'\x0c',
    'OP_PUSHBYTES_13': b'\x0d',
    'OP_PUSHBYTES_14': b'\x0e',
    'OP_PUSHBYTES_15': b'\x0f',
    'OP_PUSHBYTES_16': b'\x10',
    'OP_PUSHBYTES_17': b'\x11',
    'OP_PUSHBYTES_18': b'\x12',
    'OP_PUSHBYTES_19': b'\x13',
    'OP_PUSHBYTES_20': b'\x14',
    'OP_PUSHBYTES_21': b'\x15',
    'OP_PUSHBYTES_22': b'\x16',
    'OP_PUSHBYTES_23': b'\x17',
    'OP_PUSHBYTES_24': b'\x18',
    'OP_PUSHBYTES_25': b'\x19',
    'OP_PUSHBYTES_26': b'\x1a',
    'OP_PUSHBYTES_27': b'\x1b',
    'OP_PUSHBYTES_28': b'\x1c',
    'OP_PUSHBYTES_29': b'\x1d',
    'OP_PUSHBYTES_30': b'\x1e',
    'OP_PUSHBYTES_31': b'\x1f',
    'OP_PUSHBYTES_32': b'\x20',
    'OP_PUSHBYTES_33': b'\x21',
    'OP_PUSHBYTES_34': b'\x22',
    'OP_PUSHBYTES_35': b'\x23',
    'OP_PUSHBYTES_36': b'\x24',
    'OP_PUSHBYTES_37': b'\x25',
    'OP_PUSHBYTES_38': b'\x26',
    'OP_PUSHBYTES_39': b'\x27',
    'OP_PUSHBYTES_40': b'\x28',
    'OP_PUSHBYTES_41': b'\x29',
    'OP_PUSHBYTES_42': b'\x2a',
    'OP_PUSHBYTES_43': b'\x2b',
    'OP_PUSHBYTES_44': b'\x2c',
    'OP_PUSHBYTES_45': b'\x2d',
    'OP_PUSHBYTES_46': b'\x2e',
    'OP_PUSHBYTES_47': b'\x2f',
    'OP_PUSHBYTES_48': b'\x30',
    'OP_PUSHBYTES_49': b'\x31',
    'OP_PUSHBYTES_50': b'\x32',
    'OP_PUSHBYTES_51': b'\x33',
    'OP_PUSHBYTES_52': b'\x34',
    'OP_PUSHBYTES_53': b'\x35',
    'OP_PUSHBYTES_54': b'\x36',
    'OP_PUSHBYTES_55': b'\x37',
    'OP_PUSHBYTES_56': b'\x38',
    'OP_PUSHBYTES_57': b'\x39',
    'OP_PUSHBYTES_58': b'\x3a',
    'OP_PUSHBYTES_59': b'\x3b',
    'OP_PUSHBYTES_60': b'\x3c',
    'OP_PUSHBYTES_61': b'\x3d',
    'OP_PUSHBYTES_62': b'\x3e',
    'OP_PUSHBYTES_63': b'\x3f',
    'OP_PUSHBYTES_64': b'\x40',
    'OP_PUSHBYTES_65': b'\x41',
    'OP_PUSHBYTES_66': b'\x42',
    'OP_PUSHBYTES_67': b'\x43',
    'OP_PUSHBYTES_68': b'\x44',
    'OP_PUSHBYTES_69': b'\x45',
    'OP_PUSHBYTES_70': b'\x46',
    'OP_PUSHBYTES_71': b'\x47',
    'OP_PUSHBYTES_72': b'\x48',
    'OP_PUSHBYTES_73': b'\x49',
    'OP_PUSHBYTES_74': b'\x4a',
    'OP_PUSHBYTES_75': b'\x4b', """
    'OP_PUSHDATA1': b'\x4c',
    'OP_PUSHDATA2': b'\x4d',
    'OP_PUSHDATA4': b'\x4e',
    'OP_1NEGATE': b'\x4f',
    'OP_RESERVED': b'\x50',
    'OP_1': b'\x51',
    'OP_2': b'\x52',
    'OP_3': b'\x53',
    'OP_4': b'\x54',
    'OP_5': b'\x55',
    'OP_6': b'\x56',
    'OP_7': b'\x57',
    'OP_8': b'\x58',
    'OP_9': b'\x59',
    'OP_10': b'\x5a',
    'OP_11': b'\x5b',
    'OP_12': b'\x5c',
    'OP_13': b'\x5d',
    'OP_14': b'\x5e',
    'OP_15': b'\x5f',
    'OP_16': b'\x60',
    'OP_PUSHNUM_1': b'\x51',
    'OP_PUSHNUM_2': b'\x52',
    'OP_PUSHNUM_3': b'\x53',
    'OP_PUSHNUM_4': b'\x54',
    'OP_PUSHNUM_5': b'\x55',
    'OP_PUSHNUM_6': b'\x56',
    'OP_PUSHNUM_7': b'\x57',
    'OP_PUSHNUM_8': b'\x58',
    'OP_PUSHNUM_9': b'\x59',
    'OP_PUSHNUM_10': b'\x5a',
    'OP_PUSHNUM_11': b'\x5b',
    'OP_PUSHNUM_12': b'\x5c',
    'OP_PUSHNUM_13': b'\x5d',
    'OP_PUSHNUM_14': b'\x5e',
    'OP_PUSHNUM_15': b'\x5f',
    'OP_PUSHNUM_16': b'\x60',
    # Flow control
    'OP_NOP': b'\x61',
    'OP_IF': b'\x63',
    'OP_NOTIF': b'\x64',
    'OP_ELSE': b'\x67',
    'OP_ENDIF': b'\x68',
    'OP_VERIFY': b'\x69',
    'OP_RETURN': b'\x6a',
    # Stack operations
    'OP_TOALTSTACK': b'\x6b',
    'OP_FROMALTSTACK': b'\x6c',
    'OP_2DROP': b'\x6d',
    'OP_2DUP': b'\x6e',
    'OP_3DUP': b'\x6f',
    'OP_2OVER': b'\x70',
    'OP_2ROT': b'\x71',
    'OP_2SWAP': b'\x72',
    'OP_IFDUP': b'\x73',
    'OP_DEPTH': b'\x74',
    'OP_DROP': b'\x75',
    'OP_DUP': b'\x76',
    'OP_NIP': b'\x77',
    'OP_OVER': b'\x78',
    'OP_PICK': b'\x79',
    'OP_ROLL': b'\x7a',
    'OP_ROT': b'\x7b',
    'OP_SWAP': b'\x7c',
    'OP_TUCK': b'\x7d',
    # Bitwise logic
    'OP_INVERT': b'\x83',
    'OP_AND': b'\x84',
    'OP_OR': b'\x85',
    'OP_XOR': b'\x86',
    'OP_EQUAL': b'\x87',
    'OP_EQUALVERIFY': b'\x88',
    # Arithmetic operations
    'OP_1ADD': b'\x8b',
    'OP_1SUB': b'\x8c',
    'OP_NEGATE': b'\x8f',
    'OP_ABS': b'\x90',
    'OP_NOT': b'\x91',
    'OP_0NOTEQUAL': b'\x92',
    'OP_ADD': b'\x93',
    'OP_SUB': b'\x94',
    'OP_MUL': b'\x95',  # disabled
    'OP_DIV': b'\x96',  # disabled
    'OP_MOD': b'\x97',  # disabled
    'OP_LSHIFT': b'\x98',  # disabled
    'OP_RSHIFT': b'\x99',  # disabled
    'OP_BOOLAND': b'\x9a',
    'OP_BOOLOR': b'\x9b',
    'OP_NUMEQUAL': b'\x9c',
    'OP_NUMEQUALVERIFY': b'\x9d',
    'OP_NUMNOTEQUAL': b'\x9e',
    'OP_LESSTHAN': b'\x9f',
    'OP_GREATERTHAN': b'\xa0',
    'OP_LESSTHANOREQUAL': b'\xa1',
    'OP_GREATERTHANOREQUAL': b'\xa2',
    'OP_MIN': b'\xa3',
    'OP_MAX': b'\xa4',
    'OP_WITHIN': b'\xa5',
    # Crypto operations
    'OP_RIPEMD160': b'\xa6',
    'OP_SHA1': b'\xa7',
    'OP_SHA256': b'\xa8',
    'OP_HASH160': b'\xa9',
    'OP_HASH256': b'\xaa',
    'OP_CODESEPARATOR': b'\xab',
    'OP_CHECKSIG': b'\xac',
    'OP_CHECKSIGVERIFY': b'\xad',
    'OP_CHECKMULTISIG': b'\xae',
    'OP_CHECKMULTISIGVERIFY': b'\xaf',
    # Reserved or non-standard opcodes
    'OP_NOP1': b'\xb0',  # reserved
    'OP_CHECKLOCKTIMEVERIFY': b'\xb1',
    'OP_CHECKSEQUENCEVERIFY': b'\xb2',
    'OP_CSV': b'\xb2',  # same as OP_CHECKSEQUENCEVERIFY
    'OP_NOP4': b'\xb3',  # reserved
    'OP_NOP5': b'\xb4',  # reserved
    'OP_NOP6': b'\xb5',  # reserved
    'OP_NOP7': b'\xb6',  # reserved
    'OP_NOP8': b'\xb7',  # reserved
    'OP_NOP9': b'\xb8',  # reserved
    'OP_NOP10': b'\xb9',  # reserved
    'OP_CHECKSIGADD': b'\xba',
    'OP_CHECKSIGADDVERIFY': b'\xbb',

}
